name: Allure Report

on:
  push:
    branches:
      - main

jobs:
  allure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Allure
      run: sudo apt-add-repository ppa:qameta/allure -y && sudo apt-get update && sudo apt-get install allure -y

    - name: Generate Allure report
      run: allure generate allure-results --clean

    - name: Deploy Allure report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
